version: 2
updates:
- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: weekly
    time: "23:00"
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
